# Generated by Django 4.2.5 on 2023-09-12 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('bio', models.TextField(default='I Love This APP', max_length=256)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('age', models.IntegerField(default=18)),
                ('weight', models.FloatField(default=50.45)),
                ('status', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
