# Generated by Django 4.2.7 on 2023-11-30 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_description_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesorios_name', models.CharField(default='Accesorio Generico', max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField(default='Descripcion de accesorio generico', max_length=150)),
                ('image', models.ImageField(default='default-image.jpg', upload_to='images/')),
                ('stock', models.PositiveSmallIntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
    ]
