# Generated by Django 4.2.7 on 2023-11-30 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_accesorios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recargas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recarga_name', models.CharField(default='Recarga Generica', max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField(default='Descripcion de la recarga generica', max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
    ]
