# Generated by Django 4.2.7 on 2023-11-30 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_recargas'),
    ]

    operations = [
        migrations.AddField(
            model_name='recargas',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='Plan Generico', max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField(default='Descripcion del plan generico', max_length=150)),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
    ]
