# Generated by Django 4.2.7 on 2023-11-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_recargas_status_planes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default-image.jpg', upload_to='media/'),
        ),
    ]
