# Generated by Django 4.2.5 on 2023-12-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorios',
            name='image',
            field=models.ImageField(default='default-image.jpg', upload_to='media/'),
        ),
    ]
