# Generated by Django 4.2.5 on 2023-12-05 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_accesorios_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
